#!/usr/bin/env sh
bspc config active_border_color '#1e1e1e'
bspc config border_width 4
bspc config borderless_monocle true
bspc config bottom_padding 0
bspc config click_to_focus 'button1'
bspc config focused_border_color '#5e81bc'
bspc config gapless_monocle true
bspc config left_padding 0
bspc config merge_overlapping_monitors true
bspc config normal_border_color '#4c566a'
bspc config pointer_action1 'move'
bspc config pointer_action2 'resize_side'
bspc config pointer_action3 'resize_corner'
bspc config pointer_modifier 'mod4'
bspc config presel_feedback_color '#5e81ac'
bspc config remove_disabled_monitors true
bspc config right_padding 0
bspc config single_monocle true
bspc config split_ratio 0.500000
bspc config top_padding 30
bspc config window_gap 5

bspc rule -a sun-awt-X11-XDialogPeer state=floating
bspc rule -a pinentry-qt state=floating

polybar default &

autorandr --change
